models:
  - name: "Base BERT"
    repo: "princeton-logion/LOGION-50k_wordpiece"
    type: "bert"

  - name: "Base ELECTRA"
    repo: "princeton-logion/base-electra"
    type: "electra"

  - name: "Some Future Model"
    repo: "path/to/future/model"
    type: "type_here"